from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Email)
admin.site.register(Logo)
admin.site.register(HeaderTitle)
admin.site.register(HeaderParagraph)
admin.site.register(YoutubeLink)
admin.site.register(BusinessSucces)
admin.site.register(BusinessCard)
admin.site.register(Reservation)
admin.site.register(Reports)
admin.site.register(SocialLink)
admin.site.register(Testimonials)
admin.site.register(Pricing)
admin.site.register(Count)
admin.site.register(Blog)
admin.site.register(BlogCards)
admin.site.register(UnderSection)
admin.site.register(Reserved)
admin.site.register(Users)
admin.site.register(WhoI)
admin.site.register(SecondPageCount)
admin.site.register(MySkills)
admin.site.register(SignUp)
admin.site.register(Skidka)
admin.site.register(Plan)
admin.site.register(PriceForBasic)
admin.site.register(PriceForAdvanced)
admin.site.register(PriceForExpert)
admin.site.register(TestimonialsCard)

