# Generated by Django 4.0.1 on 2022-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_title_alter_logo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Title',
            new_name='HeaderTitle',
        ),
    ]
