# Generated by Django 4.0.1 on 2022-01-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_businesssucces'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='businesslogo')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.CharField(max_length=255)),
                ('firstpara', models.CharField(max_length=255)),
                ('secondpara', models.CharField(max_length=255)),
                ('thirdpara', models.CharField(max_length=255)),
                ('fourthpara', models.CharField(max_length=255)),
            ],
        ),
    ]
