# Generated by Django 4.0.1 on 2022-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_businesscard_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='image',
            field=models.ImageField(default=5, upload_to='reservation'),
            preserve_default=False,
        ),
    ]
