# Generated by Django 4.0.1 on 2022-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('firstlogo', models.ImageField(upload_to='social-links')),
                ('firstpara', models.CharField(max_length=255)),
                ('firstlink', models.CharField(max_length=255)),
                ('secondlogo', models.ImageField(upload_to='social-links')),
                ('secondpara', models.CharField(max_length=255)),
                ('secondlink', models.CharField(max_length=255)),
                ('thirdlogo', models.ImageField(upload_to='social-links')),
                ('thirdpara', models.CharField(max_length=255)),
                ('thirdlink', models.CharField(max_length=255)),
            ],
        ),
    ]
