# Generated by Django 4.0.1 on 2022-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blog_count_pricing_reserved_testimonials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
