# Generated by Django 4.0.1 on 2022-01-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_whoi_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoi',
            name='firstskill',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoi',
            name='fourthskill',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoi',
            name='secondskill',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whoi',
            name='thirdskill',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
