# Generated by Django 4.0.1 on 2022-01-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skidka',
            name='skidka',
        ),
        migrations.AddField(
            model_name='plan',
            name='advancedprice',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='expertprice',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skidka',
            name='advancedskidka',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skidka',
            name='basicskidka',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skidka',
            name='expertskidka',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriceForExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('skidki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skidka')),
            ],
        ),
        migrations.CreateModel(
            name='PriceForBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('skidki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skidka')),
            ],
        ),
        migrations.CreateModel(
            name='PriceForAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plan')),
                ('skidki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skidka')),
            ],
        ),
    ]
