# Generated by Django 4.0.1 on 2022-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_skidka_skidka_plan_advancedprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='logo',
            field=models.CharField(max_length=255),
        ),
    ]
