# Generated by Django 4.0.1 on 2022-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_testimonialscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialscard',
            name='neartitle',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
