# Generated by Django 4.0.1 on 2022-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_testimonialscard_neartitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardimg', models.ImageField(upload_to='blogcards')),
                ('cardtitle', models.CharField(max_length=255)),
                ('cardpara', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cardimg',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cardpara',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cardtitle',
        ),
    ]
