# Generated by Django 4.0.1 on 2022-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blogcards_remove_blog_cardimg_remove_blog_cardpara_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcards',
            name='cardlink',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
