# Generated by Django 4.0.1 on 2022-01-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_cardpara_blogcards_cardpara1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcards',
            name='cardlink',
        ),
    ]
